name: PV Monitoring

on:
  schedule:
    - cron: "30 10,15 * * *"

  workflow_dispatch:

jobs:

  monitor:

    runs-on: ubuntu-latest

    env:
      ENERGYSOFT_USER: ${{ secrets.ENERGYSOFT_USER }}
      ENERGYSOFT_PASSWORD: ${{ secrets.ENERGYSOFT_PASSWORD }}
      BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python scripts/monitor.py